# Generated by Django 6.1.1 on 2026-09-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='material',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehiclebooking',
            name='employee',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderLine',
        ),
    ]
